"""Recommendation explainability engine.

Generates human-readable explanations via:
1. Model contribution chart (each model's % contribution to signal).
2. Confidence decomposition (model agreement, data quality, regime clarity).
3. Natural language narrative generated by Claude (or a template fallback).
"""

from __future__ import annotations

from typing import Any

import numpy as np
from pydantic import BaseModel, Field

from quantflow.config.logging import get_logger
from quantflow.signals.aggregator import AggregationResult
from quantflow.signals.recommendation import FinalRecommendation

logger = get_logger(__name__)


# ---------------------------------------------------------------------------
# Output schemas
# ---------------------------------------------------------------------------


class ContributionChart(BaseModel):
    """Breakdown of model and category contributions to the final signal.

    Attributes:
        model_contributions: Dict mapping model_name → signed contribution.
        category_contributions: Dict mapping category → weighted contribution.
        top_positive_models: Top 3 most bullish models (name, signal).
        top_negative_models: Top 3 most bearish models (name, signal).
    """

    model_contributions: dict[str, float] = Field(default_factory=dict)
    category_contributions: dict[str, float] = Field(default_factory=dict)
    top_positive_models: list[tuple[str, float]] = Field(default_factory=list)
    top_negative_models: list[tuple[str, float]] = Field(default_factory=list)


class ExplanationReport(BaseModel):
    """Full explainability report for a recommendation.

    Attributes:
        narrative: Human-readable recommendation rationale.
        contribution_chart: Model and category contribution breakdown.
        confidence_decomposition: Scores for model agreement, data quality,
            and regime clarity.
        top_features: Top predictive features driving the primary ML model
            (from SHAP if available, else signal-ranked).
        metadata: Additional diagnostics.
    """

    narrative: str
    contribution_chart: ContributionChart
    confidence_decomposition: dict[str, float] = Field(default_factory=dict)
    top_features: list[str] = Field(default_factory=list)
    metadata: dict[str, Any] = Field(default_factory=dict)


# ---------------------------------------------------------------------------
# Explainer
# ---------------------------------------------------------------------------


class RecommendationExplainer:
    """Generate explanations for final trading recommendations.

    Uses Claude (via AnthropicAgent) for narrative generation when available;
    falls back to a deterministic template otherwise.

    Args:
        anthropic_agent: Optional AnthropicAgent for LLM-generated narratives.
    """

    def __init__(self, anthropic_agent: Any | None = None) -> None:
        self._anthropic = anthropic_agent
        self._logger = get_logger(__name__)

    # ------------------------------------------------------------------
    # Public interface
    # ------------------------------------------------------------------

    async def explain(
        self,
        recommendation: FinalRecommendation,
        aggregation_result: AggregationResult,
        shap_features: dict[str, float] | None = None,
    ) -> ExplanationReport:
        """Generate a full explanation for a recommendation.

        Args:
            recommendation: The :class:`FinalRecommendation` to explain.
            aggregation_result: The :class:`AggregationResult` that produced it.
            shap_features: Optional dict mapping feature_name → SHAP value
                (from GBT model). Used to populate ``top_features``.

        Returns:
            :class:`ExplanationReport`.
        """
        contribution_chart = self._build_contribution_chart(
            recommendation, aggregation_result
        )
        confidence_decomp = self._confidence_decomposition(
            recommendation, aggregation_result
        )
        top_features = self._extract_top_features(shap_features, recommendation)

        # Generate narrative
        if self._anthropic is not None:
            narrative = await self._llm_narrative(recommendation, aggregation_result)
        else:
            narrative = self._template_narrative(recommendation, aggregation_result)

        self._logger.info(
            "Explanation generated",
            symbol=recommendation.symbol,
            recommendation=recommendation.recommendation,
            narrative_source="llm" if self._anthropic else "template",
        )

        return ExplanationReport(
            narrative=narrative,
            contribution_chart=contribution_chart,
            confidence_decomposition=confidence_decomp,
            top_features=top_features,
            metadata={
                "symbol": recommendation.symbol,
                "recommendation": recommendation.recommendation,
                "signal": recommendation.signal_strength,
            },
        )

    # ------------------------------------------------------------------
    # Private helpers
    # ------------------------------------------------------------------

    @staticmethod
    def _build_contribution_chart(
        rec: FinalRecommendation,
        agg: AggregationResult,
    ) -> ContributionChart:
        """Build the model and category contribution breakdown.

        Args:
            rec: Final recommendation with model_contributions populated.
            agg: Aggregation result with category composites.

        Returns:
            :class:`ContributionChart`.
        """
        model_contrib = dict(rec.model_contributions)

        # Category contributions from the aggregation result
        cat_contrib: dict[str, float] = {}
        for cat_name, cat_data in agg.category_composites.items():
            cat_weight = agg.category_weights.get(cat_name, 0.0)
            cat_contrib[cat_name] = round(cat_data.composite * cat_weight, 4)

        # Top positive/negative models
        sorted_pos = sorted(
            [(m, v) for m, v in model_contrib.items() if v > 0],
            key=lambda x: x[1],
            reverse=True,
        )[:3]
        sorted_neg = sorted(
            [(m, v) for m, v in model_contrib.items() if v < 0],
            key=lambda x: x[1],
        )[:3]

        return ContributionChart(
            model_contributions={m: round(v, 4) for m, v in model_contrib.items()},
            category_contributions=cat_contrib,
            top_positive_models=[(m, round(v, 4)) for m, v in sorted_pos],
            top_negative_models=[(m, round(v, 4)) for m, v in sorted_neg],
        )

    @staticmethod
    def _confidence_decomposition(
        rec: FinalRecommendation,
        agg: AggregationResult,
    ) -> dict[str, float]:
        """Decompose the overall confidence into interpretable sub-scores.

        Sub-scores:
        - model_agreement: Fraction of models agreeing on direction.
        - data_quality: Ratio of models used to available.
        - regime_clarity: Regime detection confidence.
        - vol_adjustment: Impact of volatility scaling on confidence.

        Args:
            rec: Final recommendation.
            agg: Aggregation result.

        Returns:
            Dict mapping component → score (all in [0, 1]).
        """
        # Model agreement: fraction of category composites agreeing with final signal
        final_sign = np.sign(rec.signal_strength)
        composites = [
            c.composite for c in agg.category_composites.values() if c.n_models > 0
        ]
        if composites:
            agreement = float(
                sum(1 for c in composites if np.sign(c) == final_sign) / len(composites)
            )
        else:
            agreement = 0.5

        data_quality = rec.data_quality_score
        regime_clarity = (
            float(rec.regime.regime_confidence)
            if rec.regime is not None
            else 0.5
        )
        # Vol adjustment: how much vol scaling moved the signal
        vol_adj = float(
            1.0 - abs(agg.vol_scale_factor - 1.0) / 2.0
        )
        vol_adj = float(np.clip(vol_adj, 0.0, 1.0))

        return {
            "model_agreement": round(agreement, 4),
            "data_quality": round(data_quality, 4),
            "regime_clarity": round(regime_clarity, 4),
            "vol_adjustment": round(vol_adj, 4),
        }

    @staticmethod
    def _extract_top_features(
        shap_features: dict[str, float] | None,
        rec: FinalRecommendation,
    ) -> list[str]:
        """Extract the top predictive features for the explanation.

        Uses SHAP values if available; otherwise uses the bullish / bearish
        factor lists from the recommendation.

        Args:
            shap_features: Dict mapping feature_name → SHAP value.
            rec: Final recommendation with factor lists.

        Returns:
            List of top feature strings (max 10).
        """
        if shap_features:
            sorted_feats = sorted(
                shap_features.items(), key=lambda x: abs(x[1]), reverse=True
            )
            return [f"{name} ({val:+.3f})" for name, val in sorted_feats[:10]]

        # Fallback: bullish + bearish factors
        features = list(rec.top_bullish_factors) + list(rec.top_bearish_factors)
        return features[:10]

    async def _llm_narrative(
        self,
        rec: FinalRecommendation,
        agg: AggregationResult,
    ) -> str:
        """Generate narrative using AnthropicAgent.

        Args:
            rec: Final recommendation.
            agg: Aggregation result.

        Returns:
            LLM-generated narrative string.
        """
        try:
            regime_label = rec.regime.overall_regime if rec.regime else "unknown"
            top_bull = ", ".join(rec.top_bullish_factors[:3]) or "none"
            top_bear = ", ".join(rec.top_bearish_factors[:3]) or "none"
            cat_summary = "; ".join(
                f"{name}: {c.composite:+.2f} ({c.n_models} models)"
                for name, c in agg.category_composites.items()
                if c.n_models > 0
            )

            narrative = await self._anthropic.generate_recommendation_rationale(
                symbol=rec.symbol,
                signal=rec.signal_strength,
                confidence=rec.confidence,
                bullish_factors=rec.top_bullish_factors,
                bearish_factors=rec.top_bearish_factors,
                regime=regime_label,
            )
            return narrative
        except Exception as exc:
            self._logger.warning(
                "LLM narrative generation failed, using template",
                error=str(exc),
            )
            return self._template_narrative(rec, agg)

    @staticmethod
    def _template_narrative(
        rec: FinalRecommendation,
        agg: AggregationResult,
    ) -> str:
        """Generate a deterministic template-based narrative.

        Args:
            rec: Final recommendation.
            agg: Aggregation result.

        Returns:
            Template narrative string.
        """
        action = rec.recommendation.replace("_", " ")
        signal_pct = f"{rec.signal_strength:+.0%}"
        conf_pct = f"{rec.confidence:.0%}"
        regime = rec.regime.overall_regime if rec.regime else "unknown"

        bull_text = (
            f"Key support: {', '.join(rec.top_bullish_factors[:2])}. "
            if rec.top_bullish_factors
            else ""
        )
        bear_text = (
            f"Key risks: {', '.join(rec.top_bearish_factors[:2])}. "
            if rec.top_bearish_factors
            else ""
        )
        warning_text = (
            f" Risk warnings: {'; '.join(rec.risk_warnings)}."
            if rec.risk_warnings
            else ""
        )

        return (
            f"{rec.symbol} is rated {action} with composite signal {signal_pct} "
            f"and confidence {conf_pct} in a {regime} regime. "
            f"{bull_text}{bear_text}"
            f"Suggested position size: {rec.suggested_position_size:+.1%} of max."
            f"{warning_text}"
        ).strip()
