"""Agentic intelligence endpoints.

Returns LLM-generated market intelligence reports, news sentiment,
and macro analysis.  Full analysis requires Premium subscription.
"""

from __future__ import annotations

from datetime import UTC, datetime, timedelta
from typing import Any

from fastapi import APIRouter, HTTPException, Query, status
from pydantic import BaseModel, Field
from sqlalchemy import desc, select

from quantflow.api.auth.dependencies import CurrentUser, DbDep, require_tier
from quantflow.config.constants import TIER_PREMIUM
from quantflow.config.logging import get_logger
from quantflow.db.models import AgentOutput

logger = get_logger(__name__)

router = APIRouter(tags=["intelligence"])


# ---------------------------------------------------------------------------
# Response schemas
# ---------------------------------------------------------------------------


class NewsItem(BaseModel):
    """Single news/intelligence item."""

    timestamp: datetime
    source: str
    headline: str
    sentiment: float
    url: str | None = None


class IntelligenceReport(BaseModel):
    """Full intelligence report for a symbol."""

    symbol: str
    generated_at: datetime
    overall_sentiment: float
    sentiment_regime: str
    confidence: float
    bullish_factors: list[str]
    bearish_factors: list[str]
    key_events: list[str]
    news_items: list[NewsItem]
    metadata: dict[str, Any] = Field(default_factory=dict)


class MacroReport(BaseModel):
    """Macro market intelligence report."""

    generated_at: datetime
    market_regime: str
    macro_sentiment: float
    key_themes: list[str]
    risk_factors: list[str]
    metadata: dict[str, Any] = Field(default_factory=dict)


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def _agent_row_to_report(row: AgentOutput, news: list[NewsItem]) -> IntelligenceReport:
    """Convert ORM AgentOutput to IntelligenceReport.

    Args:
        row: ORM AgentOutput row.
        news: Pre-fetched news items.

    Returns:
        :class:`IntelligenceReport`.
    """
    sentiment = row.sentiment_score
    if sentiment > 0.3:
        regime = "BULLISH"
    elif sentiment < -0.3:
        regime = "BEARISH"
    else:
        regime = "NEUTRAL"

    return IntelligenceReport(
        symbol=row.symbol,
        generated_at=row.time,
        overall_sentiment=round(sentiment, 4),
        sentiment_regime=regime,
        confidence=round(row.confidence, 4),
        bullish_factors=row.bullish_factors or [],
        bearish_factors=row.bearish_factors or [],
        key_events=row.key_events or [],
        news_items=news,
        metadata=row.model_metadata or {},
    )


# ---------------------------------------------------------------------------
# Endpoints
# ---------------------------------------------------------------------------


@router.get(
    "/{symbol}",
    response_model=IntelligenceReport,
    summary="Get latest intelligence report for a symbol",
    dependencies=[require_tier(TIER_PREMIUM)],
)
async def get_intelligence(
    symbol: str,
    user: CurrentUser,
    db: DbDep,
) -> IntelligenceReport:
    """Return the most recent LLM-generated intelligence report.

    Reports are generated by the agentic pipeline (Celery workers) and
    cached in the database.  Staleness is shown via ``generated_at``.

    Requires Premium subscription.
    """
    symbol = symbol.upper()
    result = await db.execute(
        select(AgentOutput)
        .where(AgentOutput.symbol == symbol)
        .order_by(desc(AgentOutput.time))
        .limit(1)
    )
    row = result.scalar_one_or_none()
    if row is None:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail=(
                f"No intelligence report available for '{symbol}'. "
                "Reports are generated every 4 hours for Premium users."
            ),
        )

    # Build lightweight news items from raw_sources metadata
    news_items: list[NewsItem] = []
    for src in (row.raw_sources or [])[:10]:
        news_items.append(
            NewsItem(
                timestamp=row.time,
                source="agent",
                headline=str(src)[:200],
                sentiment=row.sentiment_score,
            )
        )

    return _agent_row_to_report(row, news_items)


@router.get(
    "/{symbol}/news",
    response_model=list[NewsItem],
    summary="Get recent news items for a symbol",
)
async def get_news(
    symbol: str,
    user: CurrentUser,
    db: DbDep,
    days: int = Query(default=7, ge=1, le=30),
    limit: int = Query(default=20, ge=1, le=100),
) -> list[NewsItem]:
    """Return recent news/sentiment items from the agent pipeline.

    Free tier: 7 days max.
    Premium+: up to 30 days.
    """
    symbol = symbol.upper()
    from quantflow.config.constants import TIER_FREE

    if user.subscription_tier == TIER_FREE and days > 7:
        raise HTTPException(
            status_code=status.HTTP_403_FORBIDDEN,
            detail="Free tier is limited to 7 days of news history.",
        )

    since = datetime.now(tz=UTC) - timedelta(days=days)
    result = await db.execute(
        select(AgentOutput)
        .where(AgentOutput.symbol == symbol, AgentOutput.time >= since)
        .order_by(desc(AgentOutput.time))
        .limit(limit)
    )
    rows = result.scalars().all()

    items: list[NewsItem] = []
    for row in rows:
        for src in (row.raw_sources or [])[:3]:
            items.append(
                NewsItem(
                    timestamp=row.time,
                    source=row.agent_name,
                    headline=str(src)[:200],
                    sentiment=row.sentiment_score,
                )
            )
    return items[:limit]


@router.get(
    "/macro/report",
    response_model=MacroReport,
    summary="Get macro intelligence report",
    dependencies=[require_tier(TIER_PREMIUM)],
)
async def get_macro_report(
    user: CurrentUser,
    db: DbDep,
) -> MacroReport:
    """Return a high-level macro market intelligence summary.

    Aggregates recent agent outputs across a cross-section of macro symbols
    (SPY, QQQ, TLT, GLD, DXY) to derive a market-wide sentiment picture.

    Requires Premium subscription.
    """
    macro_symbols = ["SPY", "QQQ", "TLT", "GLD"]
    since = datetime.now(tz=UTC) - timedelta(days=3)

    result = await db.execute(
        select(AgentOutput)
        .where(
            AgentOutput.symbol.in_(macro_symbols),
            AgentOutput.time >= since,
        )
        .order_by(desc(AgentOutput.time))
        .limit(20)
    )
    rows = result.scalars().all()

    if not rows:
        # Return neutral placeholder when no data available
        return MacroReport(
            generated_at=datetime.now(tz=UTC),
            market_regime="UNKNOWN",
            macro_sentiment=0.0,
            key_themes=["Insufficient data — macro report refreshes every 4 hours."],
            risk_factors=[],
            metadata={"n_sources": 0},
        )

    avg_sentiment = float(sum(r.sentiment_score for r in rows) / len(rows))
    all_events: list[str] = []
    all_bearish: list[str] = []
    for row in rows:
        all_events.extend(row.key_events or [])
        all_bearish.extend(row.bearish_factors or [])

    if avg_sentiment > 0.3:
        regime = "RISK_ON"
    elif avg_sentiment < -0.3:
        regime = "RISK_OFF"
    else:
        regime = "NEUTRAL"

    return MacroReport(
        generated_at=datetime.now(tz=UTC),
        market_regime=regime,
        macro_sentiment=round(avg_sentiment, 4),
        key_themes=list(dict.fromkeys(all_events))[:5],
        risk_factors=list(dict.fromkeys(all_bearish))[:5],
        metadata={"n_sources": len(rows), "symbols": macro_symbols},
    )
